### ISSUE TITLE
Unrecognized option: ▒

### ISSUE THREAD

**Issue by ottuzzi** [u1f35c/mqtt-arp#2]
Hello,

  I compiled directly from git clone on Ubuntu 20.04 (Linux ubuntu 5.4.0-1016-raspi #17-Ubuntu SMP Wed Aug 19 14:54:44 UTC 2020 aarch64 aarch64 aarch64 GNU/Linux) on RPI4 but when I try to run it I get the error in the subject.

Can you help me?

Thanks in advance

**Comment by u1f35c** [comment]
Please try the update I've just pushed; use of a char rather than an int seems to have caused issues on ARM while MIPS was fine.

**Comment by ottuzzi** [comment]
Hi,

thank you very much, the fix is working as expected on arm64 too :)

Thanks again
